# Generated by Django 3.2 on 2021-05-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mergedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='MergedPdfs/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
