# Generated by Django 3.2 on 2021-05-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('userName', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=60)),
            ],
        ),
    ]
